name: Compile The New Version Luci Mihomo

on: 
  workflow_dispatch:

env:
  sdk_url: https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
  sdk_ver: 23.05
  luci_ver: 21.02
  FIRMWARE: $PWD

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Clone luci-app-mihomo dev Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install packages
        run: |
          echo "Install packages"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
  
      - name: Cache openwrt SDK
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: ${{ env.FIRMWARE }}/sdk
          key: openwrt-sdk-${{ env.sdk_ver }}

      - name: Initialization environment
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.sdk_url }}
          file_name=$(echo ${{env.sdk_url}} | awk -F/ '{print $NF}')
          mkdir sdk && tar -xJf $file_name -C ./sdk --strip-components=1
          cd sdk
          echo "src-git base https://github.com/openwrt/openwrt.git;openwrt-${{ env.sdk_ver }}" > feeds.conf
          echo "src-git packages https://github.com/openwrt/packages.git;openwrt-${{ env.sdk_ver }}" >> feeds.conf
          echo "src-git luci https://github.com/openwrt/luci.git;openwrt-${{ env.sdk_ver }}" >> feeds.conf
          echo "src-git routing https://git.openwrt.org/feed/routing.git;openwrt-${{ env.sdk_ver }}"  >> feeds.conf
          echo "src-git mihomo https://github.com/rtaserver/OpenWrt-mihomo-Mod.git;mod" >> feeds.conf
          ./scripts/feeds update -a
          echo "CONFIG_PACKAGE_luci-app-mihomo=m" > .config
          ./scripts/feeds install -d n luci-app-mihomo
          make download -j8

      - name: Configure mihomo
        run: |
          cd sdk
          ./scripts/feeds update mihomo
          ./scripts/feeds install luci-app-mihomo
          echo "CONFIG_ALL_NONSHARED=n" > .config
          echo "CONFIG_ALL_KMODS=n" >> .config
          echo "CONFIG_ALL=n" >> .config
          echo "CONFIG_AUTOREMOVE=n" >> .config
          echo "CONFIG_LUCI_LANG_zh_Hans=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-mihomo=m" >> .config
          make defconfig
  
      - name: Compile mihomo
        id: compile
        run: |
          cd sdk
          echo "make package/luci-app-mihomo/{clean,compile} -j$(nproc)"
          make package/luci-app-mihomo/{clean,compile} -j$(nproc)
          mv bin/packages/x86_64/mihomo/ ../
          rm .config .config.old
          cd ../mihomo
          for i in $(ls); do mv $i luci-${{ env.luci_ver }}_$i; done
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
      
      - name: Delivering Package
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-mihomo-release
          path: ${{ env.FIRMWARE }}/mihomo/*.ipk